name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  release:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: swift-actions/setup-swift@v1

    - name: Build Swift app
      run: swift build -c release --arch arm64 --arch x86_64

    - name: List directory contents2
      run: ls -la .build/apple

    - name: List directory contents3
      run: ls -la .build/apple/Products/Release

    - name: Save Artifact
      uses: actions/upload-artifact@v3
      with:
        path: .build/apple/Products/Release/MacAudioWizard
